### ISSUE TITLE
Allow writing dictionaries with non string keys

### ISSUE THREAD

**Issue by rklaehn** [Actyx/cbor-data#7]
The new representation of a banyan data block is a 2-tuple, with the first element being a dictionary from offset to ipld, and the second being the compressed data as bytes.

I don't know how to write this using cbor-data, since the with_key method of DictionaryBuilder requires a string key.

The ability of having non string keys in dicts is one of the biggest advantages of CBOR over JSON. So this should be possible

**Comment by rkuhn** [comment]
done in 0.6
